services:
  django_server:
    build:
      context: .
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8001:8001
  postgres_db:
    image: postgres:16.2
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=leo123
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
